"""Per-MIME deterministic body extraction (the `draft` lifecycle step).

Produces a faithful first-pass body from a captured artifact (spec §8.1). The
LLM-driven `normalize` step lives elsewhere — the drafter writes only what it can
extract deterministically from the bytes.

Drafters are dispatched by mime-schema id (e.g. `application/application_pdf`).
The registry lets corpus repos add their own drafters for custom mime schemas
without editing this package.

Interface (per spec §7.1 / §7.4):

    draft(
        binary_path: Path,
        *,
        build: recordbuild.Build,
        corpus_root: Path,
        record_id: str,
        record_metadata: dict,
        canonical_algo: str | None = None,
    ) -> DrafterResult

The drafter builds the **content zone** by feeding its `Section` / `Segment` blocks
through `recordbuild.add_blocks(build, blocks)` — so a record is constructed via the
SAME validated ops (`add_segment` / `open_section` + body⟺lossless checks) that
`compile` replays from a manifest, not a parallel `segments.emit`. The single
construction path is shared by draft / redraft / decompose / compile / normalize, and
`recordbuild.finish(build)` (run by the caller) emits + grammar-validates it. The
drafter returns a `DrafterResult` carrying only the **metadata-zone** facts the caller
merges onto the record:

    fields       — artifact-block extended fields (per the mime schema), including a bare
                   `title` candidate when the format exposes one (the opener's MIME names
                   the provenance, so artifact fields aren't prefixed)
    embeds       — metadata-zone embeds (list of dicts: {media_type, address, transport, fields})
    description  — *(3.2)* DISCARDED by `derive.apply_drafter_result` — the frontmatter
                   `description` is a deliberate editorial override (spec §4.2.1), never a
                   drafter-authored byte-fact; the display description is derived from
                   role-marked fields instead (§4.2.3). No drafter should populate this key.
    issues       — spec §4.3.3.1 issue dicts: {id, severity, resolution, detector, address?, ...}
    canonical    — `<algo>:<hex>` if the mime schema declared a canonical_strategy; else None.
                   Also DISCARDED by `derive.apply_drafter_result` — the write path into a
                   record's `canonical:` field is disabled (spec §7.1 status note); content-
                   canonical identity stays retired under v20 (§7.9's "two tiers")
    origin_fields — non-primary-source enrichment (e.g. a media `ytdlp_*` set) → origin block
    origin_uri_aliases — URLs aliasing the captured origin (canonical/final); folded into
                   the origin block's uri: list, not artifact fields (spec §7.2)

Issues emitted by the drafter MUST use our spec's vocabulary (severity ∈ {blocking,
warning, info}; resolution ∈ {open, fixed, wontfix, superseded}; detector as a touch
identifier). Reconciliation #2.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, TypedDict


class DrafterResult(TypedDict, total=False):
    """Metadata-zone return value of a drafter (the content zone is built on the
    passed-in `recordbuild.Build` via `add_blocks`)."""

    fields: dict[str, Any]
    embeds: list[dict[str, Any]]
    description: str | None  # *(3.2)* discarded — see the module docstring
    issues: list[dict[str, Any]]
    canonical: str | None
    origin_fields: dict[str, Any]  # enrichment → origin block (spec §7.2)
    # Producer-declared overlay id, from an injected `corpus-origin-schema` meta — stamped
    # as the origin block's id (`<!--origin <id>-->`) by `_apply_drafter_result`. The way a
    # uri-less origin (e.g. an imessage-export) binds an overlay with no uri to match (§7.2).
    origin_schema: str | None
    # URLs the drafter discovers that are aliases of the captured origin (canonical
    # link, post-redirect final URL). Merged into the origin block's uri: list by
    # `_apply_drafter_result` — NOT artifact fields (spec §7.2).
    origin_uri_aliases: list[str]
    # Content-zone structural byte-marks (§4.3.2.3) attested at ingest — the address families
    # a drafter declares ownership of (currently: media-container chapters, `time=<tc>`,
    # §12.20 item 2). Each entry: `{address, level, entry}`. Merged onto the record's TOP-LEVEL
    # content zone (never inside a form section — chapters mark the container's shared
    # timeline, no span) by `corpus.derive.apply_drafter_result`/`_apply_structural_segments`,
    # prepended ahead of any existing content, additive and idempotent by (address, entry)
    # union — NOT stripped-and-regenerated by re-attest, because the currently-implemented
    # source (a yt-dlp sidecar) is one-shot and gone after ingest; see that function's
    # docstring.
    structural_segments: list[dict[str, Any]]


DrafterFn = Callable[..., DrafterResult]
REGISTRY: dict[str, DrafterFn] = {}


def register(schema_id: str) -> Callable[[DrafterFn], DrafterFn]:
    """Decorator to register a drafter keyed on its mime-schema id."""

    def decorator(fn: DrafterFn) -> DrafterFn:
        if schema_id in REGISTRY:
            raise ValueError(f"drafter already registered for schema id {schema_id!r}")
        REGISTRY[schema_id] = fn
        return fn

    return decorator


def get_drafter(schema_id: str) -> DrafterFn | None:
    """Look up the drafter for a mime-schema id (e.g. `application/application_pdf`)."""
    return REGISTRY.get(schema_id)


# Strategy registry — drafters keyed by a *draft strategy* name a mime schema declares
# (`draft.strategy: <name>`) rather than by schema id. This decouples drafter choice from
# the detected type, so one general drafter (e.g. `zip-manifest`) can serve many
# self_contained types whose representation is tuned by schema config — the drafting
# analogue of overlay-driven capture. Specialized formats (pdf/xlsx/epub) keep id-keyed
# drafters; a schema opts into a strategy only when a general drafter fits.
STRATEGY_REGISTRY: dict[str, DrafterFn] = {}


def register_strategy(strategy: str) -> Callable[[DrafterFn], DrafterFn]:
    """Decorator to register a general drafter keyed on a draft-strategy name."""

    def decorator(fn: DrafterFn) -> DrafterFn:
        if strategy in STRATEGY_REGISTRY:
            raise ValueError(f"drafter already registered for strategy {strategy!r}")
        STRATEGY_REGISTRY[strategy] = fn
        return fn

    return decorator


def get_strategy_drafter(strategy: str) -> DrafterFn | None:
    """Look up the drafter for a draft-strategy name declared by a mime schema."""
    return STRATEGY_REGISTRY.get(strategy)


# Importing the per-MIME submodules registers their drafters. The office drafters
# lazy-import their heavy deps (openpyxl / xlrd) inside their functions, so importing
# them here is safe without the `[office]` extra; docx uses only the stdlib.
from . import audio as _audio  # noqa: E402, F401
from . import docx as _docx  # noqa: E402, F401
from . import eml as _eml  # noqa: E402, F401
from . import epub as _epub  # noqa: E402, F401
from . import html as _html  # noqa: E402, F401
from . import image as _image  # noqa: E402, F401
from . import jsonfile as _jsonfile  # noqa: E402, F401
from . import mbox_manifest as _mbox_manifest  # noqa: E402, F401
from . import pdf as _pdf  # noqa: E402, F401
from . import tar_manifest as _tar_manifest  # noqa: E402, F401
from . import vcard_manifest as _vcard_manifest  # noqa: E402, F401
from . import video as _video  # noqa: E402, F401
from . import video_stream as _video_stream  # noqa: E402, F401
from . import xls as _xls  # noqa: E402, F401
from . import xlsx as _xlsx  # noqa: E402, F401
from . import zip_manifest as _zip_manifest  # noqa: E402, F401
