[package]
name = "ath-server"
version.workspace = true
edition.workspace = true

[dependencies]
ath-core = { workspace = true, features = ["sqlite"] }
axum.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
chrono.workspace = true
notify.workspace = true
uuid.workspace = true
