"""Coverage — the corpus→ledger representation ledger (`spec/ledger.md` §9).

Every in-scope record should be *represented*: cited as evidence by a fact or
interpretation, or rostered on a concept. `coverage.md` aggregates per corpus
and per source group (origin host / origin id / mime) — the record-level
backlog is queryable (`ath ledger worklist <hash>` answers the inverse), the
generated file stays readable. Regeneration sweeps every record, so it rides
`ath ledger regen --coverage`, not the default regen.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

from ledger.corpora import RegisteredCorpus
from ledger.model import CORPUS_REF_RE, FULL_HASH_RE

COVERAGE_PATH = "coverage.md"


def represented_hashes(ledger_root: Path) -> set[str]:
    """Every corpus hash the ledger cites or rosters, anywhere: roster
    `artifacts[].uri` and interpretation `based_on`/`needs[].record` are still
    raw `corpus://` strings (a plain text scan finds them), but claim evidence
    now cites a bare hash under a fact's `sources[].record` — parsed from each
    fact's JSON, since no `corpus://` substring appears in the file for it."""
    out: set[str] = set()
    for pattern in ("facts/*/*.json", "interpretations/*.json"):
        for f in ledger_root.glob(pattern):
            text = f.read_text(encoding="utf-8")
            out.update(CORPUS_REF_RE.findall(text))
            if not pattern.startswith("facts"):
                continue
            try:
                fact = json.loads(text)
            except (json.JSONDecodeError, OSError):
                continue
            for entry in (fact.get("sources") or {}).values():
                if isinstance(entry, dict):
                    h = entry.get("record")
                    if isinstance(h, str) and FULL_HASH_RE.match(h):
                        out.add(h)
    return out


def _group_key(facts: dict) -> str:
    return str(facts.get("origin.host") or facts.get("origin.id")
               or facts.get("mime") or "(no origin)")


def render_coverage(ledger_root: Path, corpora: list[RegisteredCorpus]) -> str:
    from corpus import records
    from ledger.harvest import record_facts

    covered = represented_hashes(ledger_root)
    parts = [
        "# Coverage — GENERATED\n\n"
        "The corpus→ledger representation ledger (`spec/ledger.md` §9): a record is\n"
        "**represented** when a fact or interpretation cites it as evidence or a\n"
        "concept rosters it. Regenerated by `ath ledger regen --coverage` — never\n"
        "hand-edit. The record-level backlog is queryable per group via\n"
        "`corpus find` + `ath ledger worklist <hash>`.\n"
    ]
    for corpus in corpora:
        if not corpus.available:
            parts.append(f"\n## {corpus.name}\n\n*(not on disk — skipped)*\n")
            continue
        total = Counter()
        hit = Counter()
        n_total = n_hit = 0
        for path in records.iter_record_paths(corpus.root):
            try:
                post = records.load(path)
            except Exception:
                continue
            group = _group_key(record_facts(post))
            total[group] += 1
            n_total += 1
            if str(post.metadata.get("id", path.stem)) in covered:
                hit[group] += 1
                n_hit += 1
        parts.append(f"\n## {corpus.name}\n\n{n_hit} of {n_total} records represented "
                     f"({(100 * n_hit // n_total) if n_total else 0}%).\n\n"
                     "| source | records | represented |\n|---|---:|---:|\n")
        for group, n in total.most_common():
            parts.append(f"| `{group}` | {n} | {hit.get(group, 0)} |\n")
    return "".join(parts)
