[package]
name = "ath-gui"
version.workspace = true
edition.workspace = true

[dependencies]
ath-core.workspace = true
eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true
image.workspace = true
ehttp = { version = "0.7", features = ["multipart"] }
anyhow.workspace = true
tracing.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
egui_taffy = "0.12"
egui_commonmark = "0.23"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
tracing-subscriber.workspace = true
tracing-web = "0.1"
wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "Location", "Document", "Element", "HtmlCanvasElement"] }
